// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9O3pLBbPUJBH6ZDFUYi6uKYdiThf2En4',
    appId: '1:369614081319:android:cbb29de389b9e807d0ed02',
    messagingSenderId: '369614081319',
    projectId: 'sigma-est-boy-ever-existed',
    storageBucket: 'sigma-est-boy-ever-existed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRQpsyAL2RaJIvi53as0w5VymRyziE_c',
    appId: '1:369614081319:ios:75b2b1a3f3780b60d0ed02',
    messagingSenderId: '369614081319',
    projectId: 'sigma-est-boy-ever-existed',
    storageBucket: 'sigma-est-boy-ever-existed.firebasestorage.app',
    iosClientId: '369614081319-b1jf695ih97pgdomc630nsvgdur1ihni.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasMobileFirebase',
  );

}